INCLUDE "EMU8086.INC"
ORG 100H
    
    PRINT "ILTIMOS QUYIDAGI BELGILARDAN BIRINI KIRITING : * / + -"
    PRINTN
    PRINT "SIZ TANLAGAN BELGI: "
    MOV AH, 1
    INT 21H
    MOV BELGI, AL
    ; BU YERDA BELGINI FOYDALANUVCHIDAN OLAMIZ (*, /, +, -)
    
    PRINTN
    PRINT "BIRINCHI SONNI KIRITING (0-9): "
    MOV AH, 1
    INT 21H
    SUB AL, 30H  ; KIRITILGAN BELGINI RAQAMGA AYLANTIRAMIZ (ASCII DAN)
    MOV SON1, AL
    ; BIRINCHI SONNI FOYDALANUVCHIDAN OLAMIZ VA RAQAMGA O‘ZGARTIRAMIZ
    
    PRINTN
    PRINT "IKKINCHI SONNI KIRITING (0-9): "
    MOV AH, 1
    INT 21H
    SUB AL, 30H  ; KIRITILGAN BELGINI RAQAMGA AYLANTIRAMIZ (ASCII DAN)
    MOV SON2, AL
    ; IKKINCHI SONNI FOYDALANUVCHIDAN OLAMIZ VA RAQAMGA O‘ZGARTIRAMIZ
    
    MOV BL, SON2
    MOV AX, 0
    MOV AL, SON1    
    ; SONLarni REGISTRLARGA JOYLASHTIRAMIZ, AL DA SON1, BL DA SON2
    
    CMP BELGI, 43
    JZ QOSHUV
    ; BELGI + (43 ASCII) BO‘LSA, QO‘SHISHGA O‘TAMIZ
    
    CMP BELGI, 45
    JZ AYRUV 
    ; BELGI - (45 ASCII) BO‘LSA, AYIRISHGA O‘TAMIZ
    
    CMP BELGI, 42
    JZ KOPAYTIRUV 
    ; BELGI * (42 ASCII) BO‘LSA, KO‘PAYTIRISHGA O‘TAMIZ
    
    CMP BELGI, 47
    JZ AYRUVA
    ; BELGI / (47 ASCII) BO‘LSA, BO‘LISHGA O‘TAMIZ
    
QOSHUV:
    ADD AL, BL   
    PRINTN
    PRINT "SIZ ISHLATGAN BELGI +"
    PRINTN
    PRINT "NATIJA: "
    CALL PRINT_RESULT
    JMP EXIT
    ; SON1 BILAN SON2 NI QO‘SHAMIZ VA NATIJANI CHIQARAMIZ

AYRUV:
    SUB AL, BL 
    PRINTN
    PRINT "SIZ ISHLATGAN BELGI -"
    PRINTN  
    PRINT "NATIJA: "
    CALL PRINT_RESULT
    JMP EXIT  
    ; SON1 DAN SON2 NI AYIRAMIZ VA NATIJANI CHIQARAMIZ
    
KOPAYTIRUV:
    MUL BL  
    PRINTN
    PRINT "SIZ ISHLATGAN BELGI *"
    PRINTN 
    PRINT "NATIJA: "
    CALL PRINT_RESULT
    JMP EXIT 
    ; SON1 BILAN SON2 NI KO‘PAYTIRAMIZ VA NATIJANI CHIQARAMIZ
    
AYRUVA:
    DIV BL  
    PRINTN
    PRINT "SIZ ISHLATGAN BELGI /"
    PRINTN   
    PRINT "NATIJA: "
    CALL PRINT_RESULT
    JMP EXIT
    ; SON1 NI SON2 GA BO‘LAMIZ VA NATIJANI CHIQARAMIZ

EXIT:
RET


; NATIJANI EKRANGA CHIQARISH UCHUN FUNKSIYA
PRINT_RESULT PROC
    PUSH AX
    PUSH BX
    PUSH DX
    ; REGISTRLARNI SAQLAB QO‘YAMIZ, ULAR BUZILMASIN
    
    MOV AH, 0    
    MOV BL, 10   
    MOV BH, 0    
    ; NATIJANI 10 GA BO‘LIB CHIQARISHGA TAYYORLANAMIZ
    
CONVERT_LOOP:
    DIV BL      
    ADD AH, 30H 
    PUSH AX     
    INC BH      
    MOV AH, 0   
    CMP AL, 0   
    JNZ CONVERT_LOOP
    ; NATIJANI RAQAMMA-RAQAM AJRATIB, ASCII GA O‘ZGARTIRAMIZ
    
PRINT_LOOP:
    POP AX      
    MOV DL, AH  
    MOV AH, 2   
    INT 21H     
    DEC BH      
    JNZ PRINT_LOOP
    ; RAQAMLARNI EKRANGA CHIQARAMIZ
    
    POP DX
    POP BX
    POP AX
    RET
    ; SAQLANGAN REGISTRLARNI QAYTARIB, FUNKSIYANI TUGATAMIZ
PRINT_RESULT ENDP

SON1 DB ?
SON2 DB ?
BELGI DB ?
; O‘ZGARUVCHILARNI E’LON QILAMIZ, ULARGA FOYDALANUVCHI MA’LUMOT JOYLASHADI

END